### ISSUE TITLE
Textbox

### ISSUE THREAD

**Issue by andregabba** [rogeercruz/tech-balance#3]
- Colocar no textbox o placeholder;
- Botão de clear no textbox;
- Aplicar layout de fonte e cor;

**Comment by rogeercruz** [comment]
Opa vou tocar esses itens ao longo do dia e vou te avisando

**Comment by rogeercruz** [comment]
https://tech-balance-site.herokuapp.com/index_23_green.html
https://tech-balance-site.herokuapp.com/index_23_purple.html
https://tech-balance-site.herokuapp.com/index_23_orange.html
https://tech-balance-site.herokuapp.com/index_23_pink.html
